site_name: YeastMate
site_url: https://example.com/
repo_url: https://github.com/CALM-LMU/YeastMate/
nav:
    - Introduction: 'index.md'
    - Installation: 'installation.md'
    - Get Started: 'getstarted.md'
    - Settings: 'settings.md'
    - Fiji plugin: 'fiji.md'
    - Label your images: 'label.md'
    - Train on your data: 'train.md'
    - Deploy & Build: 'build.md'
theme:
    name: readthedocs
