site_name: YeastMate
site_url: https://yeastmate.readthedocs.org/
repo_url: https://github.com/hoerlteam/YeastMate/
nav:
    - Introduction: 'index.md'
    - GUI - Installation: 'installation.md'
    - GUI - Get Started: 'getstarted.md'
    - GUI - Settings: 'settings.md'
    - GUI - Label your images: 'label.md'
    - Fiji plugin: 'fiji.md'
    - Python - Installation : 'environment.md'
    - Python - Train on your data: 'train.md'
theme:
    name: readthedocs
