site_name: YeastMate
site_url: https://yeastmate.readthedocs.org/
repo_url: https://github.com/hoerlteam/YeastMate/
nav:
    - Introduction: 'index.md'
    - GUI - Get Started: 'gui.md'
    - GUI - Settings: 'settings.md'
    - GUI - Annotate your images: 'label.md'
    - Fiji - Get Started: 'fiji.md'
    - Python - Get Started: 'python.md'
    - Python - Start Backends: 'backends.md'
    - Python - Train on your data: 'train.md'
theme:
    name: readthedocs
