site_name: YeastMate
site_url: https://yeastmate.readthedocs.org/
repo_url: https://github.com/hoerlteam/YeastMate/
nav:
    - Introduction: 'index.md'
    - Installation: 'installation.md'
    - Get Started: 'getstarted.md'
    - Settings: 'settings.md'
    - Fiji plugin: 'fiji.md'
    - Label your images: 'label.md'
    - Prepare environment: 'environment.md'
    - Train on your data: 'train.md'
theme:
    name: readthedocs
